# Generated by Django 3.2.3 on 2021-08-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
