# Generated by Django 3.2.3 on 2021-08-09 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_timetabledetail_timetable'),
        ('student_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
            preserve_default=False,
        ),
    ]
