# Generated by Django 3.2.3 on 2021-08-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_manage', '0002_attendance_classroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='registertime',
        ),
    ]
