# Generated by Django 3.2.3 on 2021-08-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_manage', '0004_auto_20210809_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancechange',
            name='attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_manage.attendance'),
        ),
    ]
